# Code/Astro Diagnostic

Hello, and welcome to the Code/Astro diagnostic assignment! Code/Astro classes will assume familiarity with many foundational Python concepts, so we made this notebook to help you self-assess your readiness for the workshop. Don't worry about getting everything right. Feel free to use the internet (online Python tutorials, etc.) to help you complete this diagnostic. If you understand every exercise here, even if you didn't get some of them the first time, you're prepared for Code/Astro.

Don't spend more than a few minutes on each exercise; if you can't figure it out after 15 minutes, move on! Aim to spend no more than 1.5 hours on assignment in total. More challenging questions in each section are marked with an asterisk (*). Come back to those after you've completed all the other questions.

### I: Types and Variables

**1.1.** Python is an object-oriented language, meaning that everything (even basic types like `int`s and `str`s) are represented as objects. Describe and give an example of each of the following types. The first is completed for you.

- `int`: integers (no decimals). Example: 345
- `str`
- `float`
- `tuple`
- `dict`
- `bool`
- `numpy.array`

**1.2.** Identify the types of the following Python objects (one per line). The first is completed for you.

In [ ]:
"foo"   # type str
1.2
{"foo": 1, "bar": 6}
100
'bar'
(1, 2, 3)
1e4
6 + 1.2

**1.3.** Check your work using the `type()` function. An example is below.

In [3]:
print(type(True))
print(type("foo"))   # type str
print(type(1.2))
print(type({"foo": 1, "bar": 6}))
print(type(100))
print(type('bar'))
print(type((1, 2, 3)))
print(type(1e4))
print(type(6 + 1.2))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'dict'>
<class 'int'>
<class 'str'>
<class 'tuple'>
<class 'float'>
<class 'float'>


**1.4.** What is the `type` of the object `foo` in the code snippet below? Comment the fourth line in to check.

In [4]:
def foo(bar):
    return bar

type(foo)

function

**1.5.** What is the `type` of the variable `foo` in the code snippet below?

In [5]:
foo = 5 + 3.4

type(foo)

float

**1.6** Access the first element of the following array, and assign it to the variable `foo`.

In [6]:
import numpy as np

my_arr = np.array([1, 2, 3])

foo = my_arr[0]

**1.7.** Access the value with key `foo` in the following dictionary, and assign it to the variable `bar`.

In [ ]:
my_dict = {'foo': 1, 'bar': 2}

** (*) 1.8**. Think through the following code. What do you expect `bar` to be at the end? Comment in the last line in the cell below and see if you were right. 

Note: [this blog post](https://medium.com/@meghamohan/mutable-and-immutable-side-of-python-c2145cf72747) is a good overview of what's going on here.

In [ ]:
foo = [1, 2, 3]
bar = foo
foo.pop() # removes the last element of the list
# print(bar)

**2.1** Define a function that takes in two integers and returns their product.

In [7]:
def prod(a, b):
    return a*b

(*) **2.2** Define a [recursive](https://www.programiz.com/python-programming/recursion) function that computes the factorial of an integer. Test your function by computing 5! (the answer should be 120).

In [9]:
def fact(a):
    if a < 0:
        return None
    if a == 0:
        return 1
    return a*fact(a-1)

fact(5)

120

Let's define and play with a simple class.

In [10]:
class Numbers(object):
    """
    Class containing two floats that computes their product & sum.

    Args:
        a (float): number 1
        b (float): number 2
    """
    
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __repr__(self):
        return "The numbers {} and {}.".format(self.a, self.b)
        
    def num_sum(self):
        """
        Compute the sum of `a` and `b`

        Returns:
            float: sum of `a` and `b`
        """
        return self.a + self.b
    
    def num_prod(self):
        """
        Compute the product of `a` and `b`

        Returns:
            float: product of `a` and `b`
        """
        return self.a * self.b
    
myNumbers = Numbers(1, 2)
print(myNumbers)
my_sum = myNumbers.num_sum()

The numbers 1 and 2.


**2.3** Use the `Numbers` class to find the product of 100 and 350, and assign the result to the variable `my_prod`.

In [11]:
obj = Numbers(100, 300)
my_prod = obj.num_prod()

(*) **2.4** Define a class `Integers` that inherits from `Numbers`. It should have an additional method, `fact_product` that computes the factorial of the product of two numbers. Instantiate your `Integers` class and compute the product of the factorial of 10 and 2 (you can use the function you defined in **2.2**).

In [16]:
class Integers(Numbers):
    def fact_product(self):
        return fact(self.a * self.b)
    
myInts = Integers(10, 2)
print(myInts)
print(myInts.fact_product())

The numbers 10 and 2.
2432902008176640000


### III. Imports

**3.1** Consider the following line of code:

``import scipy.ndimage``

Using this line of code as an example, explain the difference between packages and modules. Do all packages need modules and do all modules need packages?

**3.2** I want to use the following functions from python's `math` module: `sqrt`, `sin`, `cos`, `tan`. Write a single line of code that imports all four of these functions (there are multiple solutions). Note that it is not recommended to use the wildcard `*` when importing as it often imports many other variables, which can have unintended consequences!

In [17]:
from math import sqrt, sin, cos, tan

**3.3** Import the package `numpy` as the variable `np` and evaluate sin(0.5) using the `sin` function available in both `math` and  `numpy`.  Do they agree?

In [18]:
import numpy as np
np.sin(0.5), sin(0.5)

(0.479425538604203, 0.479425538604203)

### IV: String Formatting

**4.1** Use string formatting to print out the randomly generated number stored in the variable `rand` to 5 decimal places. For example, if the random number is 0.12984737, the output should be `0.12985`. In the code below, we have already generated the random number for you.

In [30]:
import random
rand = random.random()

print(f"{rand:.5f}")

0.15347


**4.2** Use string formatting to print out your python version and your python executable directory. We have stored your python executable directory in `python_dir`, your python major version number in `python_version_major`, and your python minor version number in `python_version_minor`. For example, if my python executable is in `/home/codeastro/anaconda3`, my python major version number is `3`, and my python minor version number is `8`, I should print out the following:

`Python 3.8 can be run from /home/codeastro/anaconda3 folder`

In [32]:
import sys
python_dir = sys.prefix
python_version_major = sys.version_info.major
python_version_minor = sys.version_info.minor

print(f"Python {python_version_major}.{python_version_minor} can be run from {python_dir} folder")

Python 3.8 can be run from /Users/ss4833/opt/anaconda3/envs/shubh folder


### V: Lists

Here are three different ways to construct a list

1. Within a loop
1. Using list comprehension (see https://www.pythonforbeginners.com/basics/list-comprehensions-in-python)
1. Using the multiplication property of lists (see https://thehelloworldprogram.com/python/python-list-operations/)

First, lets create a 100-element long list filled with zeros using a for loop

In [33]:
zeros = []
for i in range(100):
    zeros.append(i)

**5.1** Now use list multiplication to create the same 100-element long list filled with zeros

In [34]:
zeros = [0] * 100

(*) **5.2** Use list comprehension to create a list containing all even numbers between 0 and 100 with a single line of code.

In [35]:
evenNum = [x for x in range(0, 100, 2)]
print(evenNum)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


As you saw in exercise 5.1, list operators operate on the entire list, not on the individual elements.

**5.3** Add 1 to each element in the list. Save the modified list into a new variable called "ones"

In [37]:
ones = np.array(zeros) + 1

### VI: Numpy Arrays

It is quite common in astronomy and many other applications to perform mathematical operations on each element of a list or array. Using the built-in Python list type forces you to loop over the items in the list and operate on the elements one at a time. Looping over long lists in Python is very slow and bad practice.

Using numpy arrays allows for operations to be performed on an entire array at once. In reality a loop is still happening, but the numpy team programmed the loop in C so that it is much much faster.

Numpy can do a lot more than vector operations. Its a large, powerful package that you will use very often. See https://numpy.org for more information.

This example illustrates the different behavior for the + operator for lists and arrays.

In [41]:
import numpy as np

x = [1, 2, 3, 4, 5]
# lets divide each element by 2
for i in range(len(x)):
    x[i] /= 2
    
# Now lets do the same with a numpy array
x = np.array([1, 2, 3, 4, 5])
x = x / 2

# See how easy!

# We can also create arrays with more than one dimension
# this creates a 3D array with shape 10 rows by 12 columns
arr = np.zeros((10, 12))

# use the .shape attribute of the array to check the shape
print(arr.shape)

# We can use indexing and slicing to extract and/or operate on a subset of an array
# see https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/
# lets add 1 to the single element that is in the 0th position in both the rows and columns
arr[0, 0] = 1

# now add 10 to everything in the in the 0th row (first dimension)
arr[0, :] += 10
# now everything in the 10th column (second dimension)
arr[:, 10] += 10
# now every other element in the 4th row
arr[4, ::2] += 10

print(arr)

(10, 12)
[[11. 10. 10. 10. 10. 10. 10. 10. 10. 10. 20. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [10.  0. 10.  0. 10.  0. 10.  0. 10.  0. 20.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]]


**6.1** Create a 9x9 array filled with 1 in every element. Hint: there is a `np.ones` function too.

In [42]:
x = np.ones((9, 9))

**6.2** Multiply every element in the 0th row by 100 using slicing

In [43]:
x[0, :] *= 100
print(x)

[[100. 100. 100. 100. 100. 100. 100. 100. 100.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]]


Your array should now look like this

(*) **6.3** Extract every 3rd element from the 4th column of the array that you created in step 6.2

In [45]:
x[::3, 4]

array([100.,   1.,   1.])

**6.4** Reshape the array into a 1-dimensional vector

In [48]:
x.reshape((1, 81))

array([[100., 100., 100., 100., 100., 100., 100., 100., 100.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.]])

**6.5** Modify the 4th element of the vector x. Change the value to 20.

In [49]:
x = np.array([0, 1, 2, 3, 4, 5, 6])
y = x
x[4] = 20

**6.6** Print the 4th element of the vector y. Was y also modified as a result of modifying x?

In [50]:
print(x[4], y[4])

20 20


If I wanted to loop over the lines of a file and append each line to a list but I don't know how many lines are in the file, would it be more appropriate to use a list or an array?

If I needed to calculate the square root of 10000 numbers would it be better to use a list or an array?

### VII: Dictionaries

**7.1** Construct a dictionary where the keys are the elements of the `lorem` list below and the values are the 2nd character in each word. First construct this dictionary using a loop, then construct the same dictionary using dictionary comprehension. See here https://www.geeksforgeeks.org/python-dictionary-comprehension/ for dictionary comprehension syntax.

In [ ]:
lorem = ['Lorem', 'ipsum', 'dolor', 'sit', 'amet,', 'consectetur',
         'adipiscing', 'elit,', 'sed', 'do', 'eiusmod', 'tempor',
         'incididunt', 'ut', 'labore', 'et', 'dolore', 'magna', 'aliqua.']

**7.2** Update the values to 0 for the following keys without using a loop. Hint: lookup the `update` method for Python dictionaries

In [ ]:
changes = ['dolor', 'elit', 'tempor', 'magna']

**7.3** Loop over the key value pairs and print each pair in the following format `<key>: <value>`

**7.4** Remove all key/value pairs where the value is "o"